### ISSUE TITLE
Who is maintainer?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/field_validation#2]
This module seems to be pretty preliminary. Who is the maintainer? Should we put up a notice that someone can take it over if no maintainer?

**Comment by laryn** [comment]
https://github.com/backdrop-ops/contrib/issues/314

**Comment by jenlampton** [comment]
I've added myself as a maintainer, but I'm leaving "Seeking additional maintainers" incase anyone wants to join me :)
