### ISSUE TITLE
Undefined variable error

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/field_validation#4]
I'm interested in this module and now see that you asked for help testing it.
https://github.com/backdrop-ops/contrib/issues/314

**Enabled:**

Field Validation
Field Validation UI
Field Validation Extras

I have not been able to get it to do much of anything. So, I'll just start simple. With the module enabled and working on a content type, I start getting the following errors. 

`Notice: Undefined variable: op_col in field_validation_ui_form_field_ui_field_overview_form_alter() (line 154 of /var/www/.../.../.../modules/triplo/field_validation/field_validation_ui.module).`

`Notice: Undefined variable: op_count in field_validation_ui_form_field_ui_field_overview_form_alter() (line 154 of /var/www/.../.../.../modules/triplo/field_validation/field_validation_ui.module).`

**Comment by herbdool** [comment]
I've fixed this. Instead of trying to add another column in a complicated way, we just need to another link to the operations dropdown.
